#!/bin/bash 
#
# Copyright (C) 2013 Coder of Salvation 
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
TMPFILE="/tmp/.bashdownrss.$(whoami)"
SELF_PATH="$(dirname "$(readlink -f "$0")" )"

feeds(){
  find $TMPFILE* -type d | while read feed; do 
    rss="$(echo "$feed" | sed "s/.*$(whoami)\.//g")"
    printf "  %-20s => %s\n" "$rss" "$feed" 
  done
}

print(){
  RSSNAME="$1"; RSSMAXITEMS="$2"
  PUBDATE="$(date -R)"
  cat "$SELF_PATH/rss.bashdown" | fetch 
}

printitems(){
  RSSNAME="$1"; RSSMAXITEMS="$2"
  find $TMPFILE.$RSSNAME/* | tail -n$RSSMAXITEMS > $TMPFILE.$RSSNAME.items
  while read file; do 
    source "$file"; 
    cat $SELF_PATH/rssitem.bashdown | fetch
  done < $TMPFILE.$RSSNAME.items
}

add(){
  rssname="$1"; title="$2"; link="$3"; dir="$TMPFILE.$rssname"; file="$dir/$(date +%s).bash"
  description="$(cat - )"
  [[ ${#title} == 0 ]] && title="${description:0:20}"
  [[ ! -d "$dir" ]] && mkdir "$dir"
  echo "TITLE='$title'" > "$file"
  echo "DESC='$title'" >> "$file"
  echo "LINK='$link'"  >> "$file"
  echo "DATE='$(date -R)'"  >> "$file"
  echo "GUID='$(date +%s)'"  >> "$file"
  return 0
}

fetch(){
  IFS=''; cat - | while read line; do 
    line="$(eval "echo \"$( echo "$line" | sed 's/"/\\"/g')\"")"; # process bash in snippet
    echo "$line"
  done
}

reset(){
  rm -rf $TMPFILE*
}

_usage(){
  txt='Usage: 

  add:        echo "some message" | bashdownrss your.rss [title] [link]
  feeds:      lists all active feeds 
  append:     bashdownrss reset your.rss
  print:      bashdownrss print your.rss [maxitems]
  '; echo "$txt"; exit 1
}

if [[ "$1" == "add" ]]; then 
  cat - | add "$2" "$3" "$4"
  [[ -n $DEBUG ]] && find $TMPFILE*
else
  [[ ! -n $1 ]] && _usage
  "$@"
fi
